version: 1.0.{build}
image: Ubuntu
environment:
  DATABASE_URL: "file:./dev.db"
install:
  - sh: npm ci
test_script:
  - sh: npm run test
on_success:
  - sh: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
